apiVersion: v1
kind: PersistentVolume
metadata:
  name: cchess-logs
  labels:
    volume: cchess-logs
spec:
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node
              operator: In
              values:
                - A
  capacity:
    storage: 10Mi
  local:
    path: /var/k8s/logs